### ISSUE TITLE
Crashes with capistrano when compiling assets

### ISSUE THREAD

**Issue by leifcr** [crowdfavorite/gem-steps#1]
Seems to trigger a crash when using capistrano and having a nice message when compiling assets. I havent been able to figure it out yet, but if I don't include the line to use steps before precompiling assets, everything works as intended.

deploy.rb used (quite basic)

This was used with a very small RoR application for testing purposes.

``` ruby
# Prettier output with steps

require 'steps'

logger.level = Capistrano::Logger::IMPORTANT

load "deploy/assets"

require "bundler/capistrano"
require "rvm/capistrano"

set :application, 'cap_test'
set :repository,  "https://github.com/leifcr/capistrano-testing.git"
set :scm, :git

set :rvm_ruby_string, '1.9.3-p448@cap_test'
set :rvm_type, :system

set :user, 'deploy'
set :group, 'www-data'

set :use_sudo, false

set :normalize_asset_timestamps, false

set :current_stage, "production"
set :deploy_env, "production"
set :deploy_to, "/web/production/cap_test"
set :branch, 'master'

set :bundle_flags, "--deployment --full-index --without=development test --quiet"

role :web, "10.10.10.100"                            # Your HTTP server, Apache/etc
role :app, "10.10.10.100"                            # This may be the same as your `Web` server
role :db,  "10.10.10.100", :primary => true          # This is where Rails migrations will run

before "deploy:assets:clean"      do start_to "Clean" end
after "deploy:assets:clean"       do success end

before "deploy:assets:precompile" do start to "Compile Assets" end
after "deploy:assets:precompile"  do success end
```

Output

```
/Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/variables.rb:122:in `method_missing_with_variables': undefined method `to' for #<Capistrano::Configuration:0x007fe282b7e730> (NoMethodError)
    from ./config/deploy.rb:62:in `block in load'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/callback.rb:25:in `call'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/callback.rb:25:in `call'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:23:in `invoke_task_directly_with_callbacks'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:234:in `block (3 levels) in load'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:56:in `transaction'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:233:in `block (2 levels) in load'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:201:in `block (2 levels) in load'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/leif/.rvm/gems/ruby-1.9.3-p448@cap_test/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
```

**Comment by jondavidjohn** [comment]
Looks like you missed  an underscore

``` ruby
...
before "deploy:assets:precompile" do start to "Compile Assets" end
...                                       ^
```

Note the error message (emphasis mine)

undefined method '**to**' ...

**Comment by leifcr** [comment]
Doh. Sorry about that. I even typed it manually a few times and didn't see
that one.

Thanks for seeing my mistake
